name: msshell

 

on:
  push:
    branches:
      - "main"

 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
        -name: Checkout
        uses: actions/checkout@v3
    
        -name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mizukix16 }}
          password: ${{ secrets.PasswordAzure@ }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.mizukix16 }}/mizukix16
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{https://msshell.azurewebsites.net/}}
    
